In [1]:
#covert list to numpy
import numpy as np 
list= [10,20,30,40,50]
arr= np.array(list)
print(arr)

[10 20 30 40 50]


In [8]:
#reverse numpy array
import numpy as np

arr= np.array([1,2,3,4,5])
reverse = arr[::-1]
print(reverse)

[5 4 3 2 1]


In [9]:
#perform arithmetic operations 
import numpy as np
a=np.array([18,12,6])
b= np.array([3,2,1])

print("addition:", a+b)
print("subtraction:", a-b)
print("multiplication:", a*b)
print("division:", a/b)

addition: [21 14  7]
subtraction: [15 10  5]
multiplication: [54 24  6]
division: [6. 6. 6.]


In [11]:
#extract first row and last column
import numpy as np

arr= np.array([[1,2,3,4],
               [5,6,7,8],
               [9,10,11,12],
               [13,14,15,16]])

print("first row:", arr[0])
print("last column:", arr[:,-1])


first row: [1 2 3 4]
last column: [ 4  8 12 16]


In [16]:
#extract first two rows and last two columns
import numpy as np

arr= np.array([[1,2,3,4],
               [5,6,7,8],
               [9,10,11,12],
               [13,14,15,16]])
print("first two rows:", arr[:2])
print("first two columns:", arr[:2,:2])

first two rows: [[1 2 3 4]
 [5 6 7 8]]
first two columns: [[1 2]
 [5 6]]
